version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    networks:
      - debezium-docker-net
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment: 
      - TZ=Asia/Seoul
  kafka:
    image: debezium/kafka:1.4
    networks:
      - debezium-docker-net
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - TZ=Asia/Seoul
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: megachj/debezium.mysql_example:1.0
    networks:
      - debezium-docker-net
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=debezium
      - MYSQL_PASSWORD=debeziumpw
  debezium1:
    image: debezium/connect:1.4
    networks:
      - debezium-docker-net
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - kafka
      - mysql
    environment:
      - TZ=Asia/Seoul
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=mysql-source-connector-group
      - CONFIG_STORAGE_TOPIC=sunset_connect_configs
      - OFFSET_STORAGE_TOPIC=sunset_connect_offsets
      - STATUS_STORAGE_TOPIC=sunset_connect_statuses
      - OFFSET_FLUSH_TIMEOUT_MS=60000
  debezium2:
    image: debezium/connect:1.4
    networks:
      - debezium-docker-net
    ports:
      - '8084:8083'
    depends_on:
      - zookeeper
      - kafka
      - mysql
    environment:
      - TZ=Asia/Seoul
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=mysql-source-connector-group
      - CONFIG_STORAGE_TOPIC=sunset_connect_configs
      - OFFSET_STORAGE_TOPIC=sunset_connect_offsets
      - STATUS_STORAGE_TOPIC=sunset_connect_statuses
      - OFFSET_FLUSH_TIMEOUT_MS=60000

networks: 
  debezium-docker-net:
    external:
      name: debezium-docker-net
